--- #YAML:1.0
name: CircuitLayout
version: 0.04
license: artistic
distribution_type: module
requires:
  Math::Trig: 1.01
  Tk: 800.013
  Tk::WorldCanvas: 1.2
  perl: 5.6.0
recommends: {}
build_requires: {}
conflicts: {}
generated_by: Module::Build version 0.16
