--- #YAML:1.0
name: CircuitLayout
version: 0.0.3
license: perl
distribution_type: module
requires:
  perl: 5.6.0
recommends: {}
build_requires: {}
conflicts: {}
generated_by: Module::Build version 0.16
